using Dapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TrackerLibrary.Models;

namespace TrackerLibrary.DataAccess
{
    
    public class SqlConnector : IDataConnection
    {
        private const string db = "Tournaments";

        //****Implement inherited Interface member <CreatePerson>

        public PersonModel CreatePerson(PersonModel model)
        {
            using (IDbConnection connection = new SqlConnection(GlobalConfig.CnnString(db)))
            {
                var p = new DynamicParameters();
                p.Add("@FirstName", model.FirstName);
                p.Add("@LastName", model.LastName);
                p.Add("@EmailAddress", model.EmailAddress);
                p.Add("@PhoneNumber", model.PhoneNumber);
                p.Add("@id", 0, dbType: DbType.Int32, direction: ParameterDirection.Output);
                ///
                /// Executre SQL Database Stored Procedure: spPrize_Insert
                ///
                connection.Execute("dbo.spPeople_Insert", p, commandType: CommandType.StoredProcedure);
                /// Get the the id value back that will be generated by SQL database 
                model.Id = p.Get<int>("@id");
                return model;
            }
        }

        //*****Implement inherited Interface member <CreatePrize>

        
        /// <summary>
        /// OVERRIDING 'CreatePrize' Method inherited from 'IDataConnection' Interface. Saves a new prize to the relational SQL database
        /// </summary>
        /// <param name="model"></param>
        /// <returns>The prize info, including the unique identifier</returns>

        public PrizeModel CreatePrize(PrizeModel model)
        {
            /// SqlClient: Represents a connection to a SQL Server database.
           
            using (IDbConnection connection = new SqlConnection(GlobalConfig.CnnString(db)))
            {
                var p = new DynamicParameters();
                p.Add("@PlaceNumber", model.PlaceNumber);
                p.Add("@PlaceName", model.PlaceName);
                p.Add("@PrizeAmount", model.PrizeAmount);
                p.Add("@PrizePercentage", model.PrizePercentage);
                p.Add("@id", 0, dbType: DbType.Int32, direction: ParameterDirection.Output);
                ///
                /// Executre SQL Database Stored Procedure: spPrize_Insert
                ///
                connection.Execute("dbo.spPrizes_Insert", p, commandType: CommandType.StoredProcedure);
                /// Get the the id value back that will be generated by SQL database 
                model.Id = p.Get<int>("@id");

                return model;
            }
        }

        public List<PersonModel> GetPerson_All()
        {
            List<PersonModel> output;
            using (IDbConnection connection = new SqlConnection(GlobalConfig.CnnString(db)))
            {
                output = connection.Query<PersonModel>("dbo.spPeople_GetAll").ToList();
            }
            return output;
        }
    }
}
